name = "BranchChain"
uuid = "fc37ac16-815e-46ce-b8f2-08c670c05f0b"
version = "1.0.0-DEV"
authors = ["Ben Murrell"]

[deps]
BatchedTransformations = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
BranchingFlows = "f304b33a-538b-441c-bfb5-9e50a8d4c9a8"
CannotWaitForTheseOptimisers = "16124dda-d9fe-413b-a880-e3f4df3aa341"
DLProteinFormats = "df93d313-1126-4eb6-ac29-b325d5898587"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flowfusion = "5b4e93c8-7b6e-4682-b400-fc3b238f52b1"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardBackward = "e879419d-bb0f-4252-adee-d266c51ac92d"
HuggingFaceApi = "3cc741c3-0c9d-4fbe-84fa-cdec264173de"
InvariantPointAttention = "814a5788-1061-474f-a71f-873f087d5d12"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LearningSchedules = "7e85a9e7-c65d-495e-8ec0-baa06f07ebbf"
Onion = "fdebf6c2-71da-43a1-b539-c3bc3e09c5c6"
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomFeatureMaps = "780baa95-dd42-481b-93db-80fe3d88832c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BatchedTransformations = "0.5.8"
BranchingFlows = "0.1.0"
CannotWaitForTheseOptimisers = "0.1.3"
DLProteinFormats = "0.1.9"
Dates = "1.11.0"
Distributions = "0.25.122"
Flowfusion = "0.1.5"
Flux = "0.16.5"
ForwardBackward = "0.1.4"
HuggingFaceApi = "0.1.0"
InvariantPointAttention = "0.1.5"
JLD2 = "0.5.15, 0.6"
LearningSchedules = "0.1.0"
Onion = "0.2.16"
ProteinChains = "0.7.4"
Random = "1.11.0"
RandomFeatureMaps = "0.2.3"
StatsBase = "0.34.8"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
